### ISSUE TITLE
Electric Machines NBT issues

### ISSUE THREAD

**Issue by AngelCry** [MinecraftModDevelopment/ElectricAdvantage#2]
hi. there something wrong with few electric machines (at least furnace and crusher). i got no crash, but in log often appear things like it:
`[10:27:09] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.nbt.NBTTagEnd cannot be cast to net.minecraft.nbt.NBTTagShort
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_71]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_71]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.nbt.NBTTagEnd cannot be cast to net.minecraft.nbt.NBTTagShort
    at cyano.electricadvantage.machines.ElectricFurnaceTileEntity.loadFrom(ElectricFurnaceTileEntity.java:112) ~[ElectricFurnaceTileEntity.class:?]
    at cyano.electricadvantage.machines.ElectricMachineTileEntity.func_145839_a(ElectricMachineTileEntity.java:221) ~[ElectricMachineTileEntity.class:?]
    at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:341) ~[aqk.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:728) ~[bll.class:?]
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gt.class:?]
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gt.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_71]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_71]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]`
im using MC 1.10.2, Forge 12.18.2.2106, Power Advantage 2.3.0, Electric Advantage 2.2.0 if this helps.

**Comment by jriwanek** [comment]
Should be fixed by PR #4
